### ISSUE TITLE
Forms are not really filled

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#147]
Two examples:

Google forms

1. Go to https://forms.gle/rJjapzKfMu7SvSJR7
2. Enable translation of forms and translate
3. Fill the form
4. Submit

I can see that responses are empty

Habr

1. Go to https://habr.com/ru/feedback/
2. Make sure to switch language to Russian in the footer "Language settings"
3. Enable translation of forms and translate
4. Fill the text area
5. Observe how red hint "Обязательное поле" appears and "Log in" button is disabled - it means the form is not really filled

Inspection of <textarea> tags also shows that there is no content.

**Comment by andrenatal** [comment]
The content of the textareas are being properly posted and present in the HTTP request. I reversed engineered these pages and the issue is that they expect the native input event to be raised by the textarea in order to function like clear the placeholder in the former, and enable the submit button in the latter. I expect many pages to rely on the event.

PR is up.
