### ISSUE TITLE
In-page/HTML translation isn't properly translating/capturing all mutations

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#149]
STR:

1 - Browse to this website: https://andrenatal.com/translations-playground/ and choose a language that should be translated 
2 - Click translate
3 - Click Start mutation
4 - Notice that only the second sentence of the mutation is properly translated

**Comment by jelmervdl** [comment]
[these changes](https://github.com/mozilla/firefox-translations/compare/c5c308a55be8b39c6ad29f8d207e462b170ada47...jelmervdl:44a2c7d17080a60b9f2c7545ab98fbd600ec7b03) did the trick for me to at least get your lab experiment to work.

The source of the problem is that `startTreeWalker` doesn't consider the root node as a node it can submit for translation.  But there are some text nodes that are direct children of that root node, and these end up being skipped. The change above adds the root node as a node that can be submitted for translation.

There are some further changes to make sure that nodes that have their contents replaced are reconsidered after mutations. I also disabled the mutation observer while putting the translations back into the web page. Not sure if pausing the mutation observer is entirely necessary, but it does make reasoning about what is happening a bit easier.

**Comment by andrenatal** [comment]
Thanks for pointing that Jelmer. I observed the same situation regarding the root node. I am off until Monday and will implement it as soon I am back.
