### ISSUE TITLE
The addon should switch the required prefs itself

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#154]

**Comment by acornestean** [comment]
With the latest version of the extension, the required prefs are set by the extension, confirming the fix.

The user must still manually set the prerequisite prefs (`xpinstall.signatures.required` and `extensions.experiments.enabled`) to the required values as per https://github.com/mozilla/firefox-translations#testing and `extensions.translations.disabled` is already set tot `true` by default.

The pref `javascript.options.wasm_simd_wormhole` will be set to `true` immediately after loading the extension IF `extensions.experiments.enabled` was set to `true` and the browser restarted beforehand. So it seems that a browser restart is necessary for the prerequisite pref `extensions.experiments.enabled` to actually take effect and enable the extension.

Otherwise, the `javascript.options.wasm_simd_wormhole` will be set to `true` only after a browser restart if the prerequisite prefs are set and the browser restarted after loading the extension.

All in all, the issue is fixed.
