### ISSUE TITLE
Drastic regression on quality of at least en->pt models

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#208]
I started to notice phrases half translated, inversion of meaning, very bad translations, and those errors where words are replaced by consecutive and repeated tokens that weren't happening before. @abhi-agg do you know if something was introduced in the latest bergamot-translator that might have caused this?

Following is a screenshot with some evidence:
![Screenshot 2022-04-04 at 10-50-45 The New York Times - Breaking News US News World News and Videos](https://user-images.githubusercontent.com/973388/161605865-287a281e-3a8d-41c6-a669-ac6843dca60c.png)

<img width="1218" alt="Screen Shot 2022-04-04 at 10 53 18 AM" src="https://user-images.githubusercontent.com/973388/161606106-1d585b94-1dee-475d-900f-1d21a5e4c102.png">

**Comment by abhi-agg** [comment]
@andrenatal Was QE feature on during translation? If yes, we can try to reproduce this issue with QE feature off. If nothing changes, then we can test it with previous bergamot translator release.

However, it is unlikely that the bergamot translator update caused it because in that case we will probably see these issues with every language pair.

**Comment by andrenatal** [comment]
Both were off.

**Comment by andrenatal** [comment]
I have reverted to very old commits and still experienced the same translations and errors, so that's part of the model.
