### ISSUE TITLE
Translations does not work on non-https pages

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#237]
STR:

1 - Browse to this site: http://blogs.perl.org/users/aristotle/2022/04/ordering-ops.html
2 - Notice the translations does not work

Reason is because `crypto.subtle` [1] is not available on non-https pages [2]

[1] https://github.com/mozilla/firefox-translations/blob/main/extension/controller/translation/translationWorker.js#L544
[2]  https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle

We need to report that error to the infobar

**Comment by jelmervdl** [comment]
If you don't care about the integrity of files coming from the cache instead of remote, you can also use [`fetch`'s `integrity` option](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters).

Example: https://github.com/jelmervdl/firefox-translations/blob/c1810157652c5f1821f53bb562ffded9267f4186/extension/controller/translation/WASMTranslationHelper.js#L232-L235

(Not a great example for this issue though, since that's executed in the background-script, not the content-script. So it didn't have this issue to begin with. But using `integrity` should still work.)
