### ISSUE TITLE
Identify why infobar can't be displayed on packaged/localized versions while it can on individual binaries either from mach or from the obj folder (osx)

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#24]

**Comment by rpl** [comment]
@andrenatal As discussed over Slack:
- it may be interesting to check if there is any message logged before it happen (either in the Browser Console if the Firefox instance doesn't crash, or by making the console message to be dumped in the console if it does), there may be some race condition that happens in debug builds because they are slower and make the race actually visible to us

**Comment by andrenatal** [comment]
We won't pursue in-tree integration for now.

**Comment by andrenatal** [comment]
Thanks @rpl , but we decided to not bundle the extension anymore due lack of support.
