### ISSUE TITLE
Page action is available on HTTP pages

### ISSUE THREAD

**Issue by wagnerand** [mozilla/firefox-translations#283]
The page action is available for HTTP pages, but when you try to apply a translation, you get a note that the add-on only works on HTTPS pages.

**Comment by Rob--W** [comment]
May be preferable to resolve the issues that prevent it from working on HTTP.

**Comment by andrenatal** [comment]
I'm seeing many `self.crypto.randomUUID` on sentry, so yes, let's try to fix this...

**Comment by abhi-agg** [comment]
@wagnerand Could you please share the steps to reproduce it?

**Comment by lonnen** [comment]
To be clear, this issue is about this button: <img width="90" alt="Screen Shot 2022-05-19 at 12 16 58 PM" src="https://user-images.githubusercontent.com/21467/169385512-0eef5e15-a6b4-4e89-94b7-8a6734c21434.png">

Which is controlled by the `browser.pageAction` API

That said, I agree with Rob--W and understand the plan here is to resolve the underlying HTTP issue

**Comment by andrenatal** [comment]
I have just tested https://github.com/mozilla/firefox-translations/pull/330 on http pages (http://www.columbia.edu/~fdc/sample.html, http://www.csun.edu/~sk36711/WWW/tutorials/how_web_pages_work.html and http://info.cern.ch/ for the record) and it just translated fine. So when we sort the problem we are facing there [1], this issue should also be closed. cc @abhi-agg  

[1] https://github.com/mozilla/firefox-translations/pull/330#issuecomment-1132390299
