### ISSUE TITLE
Improved language detection

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#30]
We should have a more expanded language detection heuristic in terms of content extraction and analysis to determine the page's language instead of traversing just through divs.

**Comment by andrenatal** [comment]
Maybe we could use this https://fasttext.cc/docs/en/language-identification.html

**Comment by kpu** [comment]
According to https://github.com/mozilla/firefox-translations/pull/103#discussion_r805665729 the code `no` is coming out of CLD2 instead of `nb` and `nn`.  This is a tell that the small version of the CLD2 classifier is being used.  The full version has more languages and better accuracy (including for languages other than Norwegian).  See https://github.com/bitextor/warc2text/commit/e2543e4d2086a29c914c564aae885e7dcb888dbf for an example of using the full CLD2 classifier.  
Or use fasttext.
