### ISSUE TITLE
Sentry is never initialized in the mediator

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#305]
window.load is never raised here: https://github.com/mozilla/firefox-translations/blob/main/extension/mediator.js#L13

**Comment by andrenatal** [comment]
I'm also seeing this warning: `Sentry Logger [Warn]: Session tracking in non-browser environment with @sentry/browser is not supported.` when `Sentry.init` is called in the worker.

**Comment by Rob--W** [comment]
`window.onload` is never triggered because the content script is declared to run with `run_at` set to `document_idle`.

To make sure that there are no unnecessary requests when the user chose to not send error reporting, initialization should only happen when the consent has been given (#262).


> I'm also seeing this warning: `Sentry Logger [Warn]: Session tracking in non-browser environment with @sentry/browser is not supported.` when `Sentry.init` is called in the worker.

Looks like this can be avoided by setting `autoSessionTracking: false`.

**Comment by wagnerand** [comment]
> To make sure that there are no unnecessary requests when the user chose to not send error reporting, initialization should only happen when the consent has been given (https://github.com/mozilla/firefox-translations/issues/262).

+1 to that. It's important and something we strongly encourage add-on developers to do.
