### ISSUE TITLE
Translate Selected Text

### ISSUE THREAD

**Issue by Miserlou** [mozilla/firefox-translations#358]
I'd absolutely love it if I could highlight some text on a page, right click and translate it (see the translation and have that added to my pastebuffer when I click on it. Ideally, this would work both ways, to and from English/the system language.

**Comment by Miserlou** [comment]
Another user requests this here: https://news.ycombinator.com/item?id=31598074

**Comment by jelmervdl** [comment]
Another HN user mentioned [this extension](https://chrome.google.com/webstore/detail/zhongwen-chinese-english/kkmlkkjojmombglmlpbpapmhcaljjkde) which has such a user interface.

It might be tricky to do well with the current translation models: I'd expect users will select a single word, or just a couple of words, not a full sentence.

IIRC the training data used for the current translation models don't have much of that kind of  input. It should be doable to augment the training data to add it, but it does entail retraining models.

**Comment by woj-tek** [comment]
I second @aggroskater comment and use the same extension currently. Most of the time I only need parts of the webpage translated (usually if I'm not sure about my own translation or it's something like a fediverse with really mixed bag of languages). I virtually never use whole page translation (most of the pages I need are either in my native tongue or English)

**Comment by jelmervdl** [comment]
@woj-tek in that case, would you also like it to be able to select/auto-detect the language of just the selection? Right now the add-on only identifies the language of the page, assuming its just all in the same language. And would you mostly want to translate that then to the same output language (e.g. the same language as your Browser is using, like the add-on assumes right now)?

**Comment by woj-tek** [comment]
@jelmervdl I think something along the lines of:
1) try to translate in the specified language of the page (overwhelming majority of cases)
2) if (1) fails try to detect the language of the selection (assuming it would be possible)

As for the target language - I think it should be configurable but translating to browser language should be enough I think (sometimes I set my OS and thus browser to Spanish for immersion though when reading something online and trying to understand it better I would prefer to have it translated to English [still not my native but I think machine translation to <anything> to English would be better than <anything> to Polish :) ]).

**Comment by lonnen** [comment]
> It might be tricky to do well with the current translation models: I'd expect users will select a single word, or just a couple of words, not a full sentence.

Maybe do too much and throw some away, then optimize. Consider this straw proposal starting point:

User highlights a portion of text. We insert a non-functional custom markup tag around the highlight. It might look like:
```html
<p>He heard the voice say, "<bergamot-translation-tag>El tiempo para su trabajo ha sido concedido</bergamot-translation-tag>.</p>
```
Then we walk and chunk the whole thing like normal (or we get clever and only chunk until we queue a chunk with the closing tag, since that's all the context the engine would get anyhow. something like that). When the translated text is returned, instead of inserting it into the page we grab the inner text of the fake element and present that to the user or replace the fake tag contents with it. Finally, remove the fake tags from the page.

I'm probably missing a bunch of edge cases, here. For example, maybe we need to consider non-contiguous highlighting for some platform. How this is presented to the user is also critical. Translation in place seems to match what we already do but there are other options to consider, like a modal window injected into the page would also provide a convenient place for selecting the language.

**Comment by jelmervdl** [comment]
In https://github.com/jelmervdl/firefox-translations I've implemented a basic version of this, which just shows a popup of the translated text you selected. It assumes the text is in the same language as the rest of the page. In theory, in my implementation, you can change the from/to language via the translate button popup in the browser UI, but that's unintuitive.

@lonnen oooh I like the idea of expanding the selection to also capture some context!

**Comment by lonnen** [comment]
Thanks. No matter how we incorporate short strings into the training, the translation should always work a little better with some context to disambiguate words with multiple meanings

**Comment by bambirombi** [comment]
This is a must-have. This open-source addon has this behavior: https://simple-translate.sienori.com/

**Comment by 320x200** [comment]
Also want to add a potentially positive use case of such feature request. I'm currently learning a language, and it would be very handy to read the page in its original language, and only highlight the words, sentences and paragraphs that I am not sure about.

**Comment by okias** [comment]
I would love that for messengers like Element (where web page translation currently doesn't work). This would help translate messages in international chats a lot.

**Comment by mildlyhuman** [comment]
This would be great, especially for fediverse and twitter. 

Functionality-wise I really like [this add-on](https://addons.mozilla.org/en-US/firefox/addon/translation-selected-text/) (disclaimer i am in no way related to the author). I do not know what's its backend, but at the fron it seems to work fantastically: select text, select item in right click menu and it shows a in-page pop-up overlay box. It also does not require any permissions.

**Comment by kpu** [comment]
The present repo is abandoned.  Continued development is happening in https://github.com/jelmervdl/firefox-translations which has support for the translate selected text feature.

**Comment by mildlyhuman** [comment]
@kpu my bad, thanks for mentioning! I remembered this, but did not think when google landed me here. Will lurk in that repo.

**Comment by kpu** [comment]
We're working on launching the newer one on addons.mozilla.org and a transition plan.

**Comment by woj-tek** [comment]
@kpu why the current development version is not under /mozilla organisation (i.e. this one)? Hopefully it will be on AMO soon :-)

**Comment by okias** [comment]
What is also surprising is that it does add Chrome support together with manifest v3, which I recall Mozilla was strongly against.

**Comment by jelmervdl** [comment]
> @kpu why the current development version is not under /mozilla organisation (i.e. this one)?

The people developing that fork are part of the original Bergamot project, but not of Mozilla. We try to maintain and improve the add-on that was made for the project. But we can't make any official releases without Mozilla. And they seem to have stopped working on it since the end of the project. ([Or have they?](https://github.com/mozilla/firefox-translations/issues/515))

> Hopefully it will be on AMO soon :-)

I'll have to finish up making sure the distinction between that add-on and the Mozilla one is clear, so people won't be confused when they have installed both. Or when one has a feature/bug that the other one hasn't.

> What is also surprising is that it does add Chrome support together with manifest v3, which I recall Mozilla was strongly against.

I don't think Mozilla is strongly opposed v3 entirely, only the request blocking bits. They do have a [migration guide](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) and are actively developing support for it (luckily… because migrating to v3 is a pain but having to maintain a v2 and v3 compatible version would be worse)

**Comment by kpu** [comment]
> @kpu why the current development version is not under /mozilla organisation (i.e. this one)? Hopefully it will be on AMO soon :-)

https://addons.mozilla.org/en-US/firefox/addon/translatelocally-for-firefox/

**Comment by j-sidd** [comment]
This was also recently requested on Mozilla Connect: https://connect.mozilla.org/t5/ideas/translate-addon-highlight-to-translate/idi-p/20759

**Comment by unhammer** [comment]
My ideal flow would be:
 
1. select a paragraph 
2. right click and hit Translate
3. see a popup/modal with the text translated from Russian to Bulgarian
4. click the little buttons in the popup to change the source and target language to Hungarian→English

It should probably remember the source/target language if overridden while on the same web page, but do langid if the user has navigated to a different page (just remembering target language), though having the above parts 1-4 are the most important.

**Comment by andrenatal** [comment]
We're glad to help @aggroskater.
