### ISSUE TITLE
Addon does not appear to function properly on FF 91.9.1 Linux

### ISSUE THREAD

**Issue by viviicat** [mozilla/firefox-translations#363]
On my Firefox installation on Linux the addon is not appearing to work.
![Screenshot from 2022-06-02 13-09-59](https://user-images.githubusercontent.com/287339/171729392-ba78173e-9326-49b4-843d-ed307f10df1f.png)

Reproduction:
1. Open a page containing a different language
2. Click the translation icon in the URL bar
3. A notification bar appears at the top of the page with the text `fxtranslation-notification`, and nothing else happens.

Expected:
- I expected to see a popup prompting the language to translate to, along with translation functionality.

Actual:
- No translation functionality appears to be present.

Addon version: 1.1.2buildid20220523.151256 installed through the Addons page.
FF Version: 91.9.1esr (64-bit)
OS: Gentoo Linux 5.15.41

**Comment by cadeyrn** [comment]
I can confirm that it doesn't work with Firefox ESR 91. I don't know the requirements for this extension and if it's possible at all to make the extension compatible with Firefox ESR 91 (platform dependencies?) but Firefox ESR will make the jump to Firefox 102 in less than one month anyway. So the minimum required Firefox version should probably just be bumped to something newer.

**Comment by hanacchi** [comment]
Same issue on Windows 10.

**Comment by kpu** [comment]
Also this 1-star review: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/reviews/1843146/

**Comment by Rob--W** [comment]
This bug report has more details: https://bugzilla.mozilla.org/show_bug.cgi?id=1772793

The console shows the following relevant error:
> `notif.init is not a function`
at https://github.com/mozilla/firefox-translations/blob/99ad251a9cbe141bc7cac96693d46367d04300e9/extension/controller/experiments/TranslationBar/api.js#L155

The code there is expecting `init` to exist, because the custom element is supposed to be instantiated, and `init` is defined at https://github.com/mozilla/firefox-translations/blob/99ad251a9cbe141bc7cac96693d46367d04300e9/extension/view/js/translation-notification-fxtranslations.js#L93.

The error suggests that the custom element was not instantiated.

I guess that the issue may be caused by the `appendNotification` API change in Firefox 94, where positional arguments were replaced with an object (https://bugzilla.mozilla.org/show_bug.cgi?id=1690390, relevant diff at https://searchfox.org/mozilla-central/diff/a62618baa72cd0ba6c0a5f5fc0b1d63f2866b7c6/toolkit/content/widgets/notificationbox.js#78-222).

To have code that works for Firefox 93 and earlier, and Firefox 94 and later, you could check for the condition `notificationBox.appendNotification.length === 7` (i.e. the `notificationBox.appendNotification` method takes 7 positional arguments = Firefox 93 and earlier), and pass in the expected parameters.
