### ISSUE TITLE
Google cloud is incorrectly detected as Spanish

### ISSUE THREAD

**Issue by sylvestre** [mozilla/firefox-translations#372]
On Google cloud ( https://console.cloud.google.com/ ) logged in
![image](https://user-images.githubusercontent.com/733326/171847123-87ce722a-bfbf-4f32-b63e-1e9e89755942.png)

**Comment by padenot** [comment]
https://www.nts.live/latest is detected as being german, it's in english. No need to log in.

**Comment by padenot** [comment]
This is a snapshot of [the page](https://www.nts.live/latest) that allows reproducing. The page itself changes all the time as new radio shows are uploaded.

[nts-live-snapshot-2022-06-03.html.zip](https://github.com/mozilla/firefox-translations/files/8833346/nts-live-snapshot-2022-06-03.html.zip)

**Comment by andrenatal** [comment]
I was able to reproduce all the issues listed above and #416 fixes all them

**Comment by andrenatal** [comment]
It is working for me in the latest addon's Nightly. 

<img width="1792" alt="Screen Shot 2022-07-18 at 9 01 32 AM" src="https://user-images.githubusercontent.com/973388/179553622-17e23ccd-4a10-4759-8d5b-d9bebcde357e.png">

Sometimes manually installed unsigned addons in Fx Nightly requires a browser restart after updating the xpi and to manually delete the older versions. It's not uncommon to even need a new profile in order to have the older version totally cleared. due corruption.

Or you can set a breakpoint in this line: https://github.com/mozilla/firefox-translations/blob/main/extension/controller/backgroundScript.js#L170 and paste here the content of the `pageLanguage`, `score`,  `message.languageDetection.wordsToDetect` `cleanedWords` and `message.languageDetection.htmlElementLanguage` variables so I can see what's happening.
