### ISSUE TITLE
Page blinking followed by garbage translation

### ISSUE THREAD

**Issue by abhi-agg** [mozilla/firefox-translations#385]
Translating https://www.deutschfureuch.com/de/about/ causes issues as per this comment:

https://www.reddit.com/r/privacy/comments/v3gl2p/mozilla_releases_local_machine_translation_tools/ib6wozf/?context=3

**Comment by andrenatal** [comment]
I saw the same behavior using just Firefoz Translations

**Comment by jelmervdl** [comment]
One way to work around the interaction is replacing the MutationObserver available to the page. In https://github.com/jelmervdl/firefox-translations/commit/9b86d47243ae032804ccd6395ebbf86249066db4 I am filtering the events that the page can see, to hide the mutations caused by `InPageTranslation`. This works well, but it feels like the wrong approach.

Suggestions are very welcome at this point.
