### ISSUE TITLE
Infobar not displayed after detaching tab to new window and then re-attaching to main window

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#391]
Description:
After the infobar is displayed on any page, detaching the tab with the page to a new window, reloading the page (from the new window) and then re-attaching the tab to the main window will cause the infobar to not be displayed anymore, even after page reload. Clicking the Firefox Translations button has no effect in summoning the infobar back, as well.

Steps to reproduce:
1. Install the latest Nightly 1.1.3
2. Access any page on which the infobar should be displayed, for example https://es.wikipedia.org/wiki/Novela
3. Notice the infobar is displayed
4. Detach the tab with the page into a new window
5. Reload the page from the new window
6. The infobar is displayed on the page from the new window
7. Re-attach the tab back to the main window
8. Notice the infobar is not displayed
9. Reload the page
10. Notice the infobar is not displayed
11. Click the Firefox Translations button
12. Notice the infobar is not displayed

Actual:
After the infobar is displayed on the page from a new window, re-attaching the tab to the main window will cause the infobar to not be displayed anymore. Reloading the page or clicking the Firefox Translations button will no longer display the infobar in that tab.

Expected:
The infobar should be displayed under all circumstances when accessing a page in a supported language.

https://user-images.githubusercontent.com/50236075/172611878-fedede1e-f2d8-460d-ab35-3cc9c3ad4ec5.mp4

**Comment by acornestean** [comment]
Update: The issue also occurs with the current Release version of Firefox Translations 1.1.2. Tested on the latest Firefox Nightly and Firefox Release.

**Comment by andrenatal** [comment]
Apparently the issue here is related to the fact that this eventCallback  [1] is not called when a tab is detached.

[1] https://github.com/mozilla/firefox-translations/blob/main/extension/controller/experiments/TranslationBar/api.js#L137

**Comment by Rob--W** [comment]
I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1778534 for this.

As a work-around, you could use the `tabs.onDetached` event to detect the detachment of the tab, and do the necessary bookkeeping. In this case, since the tab is still around without being reloaded, I suggest to delete the tabId if the notification was hidden, and show the notification again if it was previously expected to be shown.

tabs.onDetached documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Tabs/onDetached
