### ISSUE TITLE
Add button to toggle between original text and translation

### ISSUE THREAD

**Issue by ajshell1** [mozilla/firefox-translations#404]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, the only way to see the original text again is to refresh the page.

**Describe the solution you'd like**
On the drop down bar that has the "Translate this tab automatically as you browse", "Participate in survey", and "Options" buttons, I'd like another button that says something like "Switch between original and translation", which would do exactly what it says it would do.

**Describe alternatives you've considered**
Maybe make this  an option that shows up when you click/right click on the icon?

**Additional context**
The other extension I use for translation, TWP - Translate Web Pages, has this this kind of feature.

**Comment by cadeyrn** [comment]
> what would you use this feature for? Do you want to see the original text for comparison or to turn the translation off?

I am not the issue opener but I have an answer. 😅 I would like to use this feature for comparison. I am not a native English speaker (as you can probably tell from my written English) but I _understand_ English well enough for most cases so most of the time I don't use a translator for English at all. _When_ I do use a translator it's either because the original text describes a topic that is harder to understand for me in a foreign language. In such a case it can be helpful for the larger context to read a translation. Or I use a translator because the original text is so long that I don't want to translate it all myself. This results in two use cases for me:

1. As we all know: machine translations are far from perfect. It is really impressive what is possible today and the results are often very good. But sometimes there are translated parts where you have the feeling that something is not right. Then I would like to check the original text for this part.
2. I run a blog in my native language (German), but most of the sources are in English. When I use a translator for a source I want to make sure that I understand it correctly so that i do not spread fake news because of translation errors. Therefore I want to check the translation for the most important parts before I use it.

**Comment by brendanjones** [comment]
Similar to Cadeyrn: I like to switch back to original language to check the original text where the English translation is a bit off, and/or there’s an important word and I want to understand the precise meaning by knowing what word was used in the original language. 

Additionally, I’m most often translating languages I can read to some extent. I prefer reading in the original language if possible, but sometimes I need help. So it’s nice to be able to quickly translate to English for the bit I was having trouble with, then switch back to the original language when I’m done (and without having to reload the page).

**Comment by marco-c** [comment]
This is available in the built-in version.

**Comment by brendanjones** [comment]
@marco-c while this is technically released, that button to switch back is not obvious, I hadn't even realised its function. Can I suggest changing the icon and adding text to the button? Or swapping the icon for text? Having it as icon-only is not consistent to the rest of the UI; all other buttons are labelled with text.

<img width="1470" alt="Screenshot 2023-07-11 at 19 08 23" src="https://github.com/mozilla/firefox-translations/assets/16049594/de12d4b0-a5e6-4b15-90b3-a613c82f843f">

**Comment by marco-c** [comment]
In the built-in version (which will be released in Firefox without addons soon), we have a "SHOW ORIGINAL" button, so that'll be much clearer.
