### ISSUE TITLE
Feature to send feedback about incorrectly translated sentences

### ISSUE THREAD

**Issue by bicolino34** [mozilla/firefox-translations#428]
**Is your feature request related to a problem? Please describe.**
Sometimes, I see sentences that were incorrectly translated and would like to submit correct translation, but currently there is no way to do it. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zopieux** [comment]
This is a great opportunity to start crowdsourcing translation quality and I believe this should be started sooner rather than later if this project ever wants to reach a somewhat decent quality. This has obvious privacy concerns which will have to be clearly stated when using the feature.

More importantly though, while this has a lot of potential for doing Good™, this will eventually attract bad actors that will attempt to rig the system to push incorrect translations by eg. organized mass-suggesting. I don't know how Mozilla intends to moderate this, but this cannot be handwaved away.

**Comment by kpu** [comment]
Right now there are several models that we know are not the best quality, like all of the beta models.  Especially Persian and Russian.  Retraining these model with time and care will improve the quality dramatically.  There isn't much point in soliciting feedback about them.  So our focus is on a project that will improve the coverage and quality of the models.

**Comment by kpu** [comment]
@zopieux There's a paper on this attack: https://aclanthology.org/2021.findings-acl.127.pdf

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
We are considering this feature for the built-in version.
