### ISSUE TITLE
Add telemetry for outbound translation

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#43]
when it's stable

**Comment by andrenatal** [comment]
Closed in favor of https://github.com/mozilla/firefox-translations/issues/54

**Comment by andrenatal** [comment]
Actually is better to decouple this and implement after #54 has landed

**Comment by andrenatal** [comment]
We need to know from @kpu and the UI team what are the metrics to be captured here.

**Comment by ChrisBurnsOneOne** [comment]
Desirable telemetry would be :

Elapsed time plugin was used
Character count of source text
No. of edits to all text boxes (i.e. no of "clicked in and out" of the text boxes)
System or OS language in use
Geographical location of the user
mouse clicks per plugin session
Which plugin functions were activated or deactivated by the user during the session

**Comment by eu9ene** [comment]
@ChrisBurnsOneOne thank you for providing the metrics! Just to make sure we're on the same page, could you please formulate questions that you want to answer using these metrics?

**Comment by ChrisBurnsOneOne** [comment]
The plugin has a limited amount of functionality which the user can truly interact with and it serves no purpose to them (or us) to deactivate or otherwise downgrade those functions. To truly run an experiment we need to compare user experiences in a highly controlled and systematic way. Since we can't really do this because such functionality was never designed to exist in the plugin from the outset, even with tailored, multiple versions of the plugin for comparison with each other, really, all we're left with is surveying user engagement.

So : 
Elapsed time plugin was used
Character count of source text
No. of edits to all text boxes (i.e. no of "clicked in and out" of the text boxes)
mouse clicks per plugin session
Which plugin functions were activated or deactivated by the user during the session (I would add here, "if at all")

- are all intended as basic measures of user engagement / use of the plugin. It would also be good to get the actual translated text, but that would undoubtedly obviously be much too intrusive.

For the remaining two : 
System or OS language in use
Geographical location of the user

-We may gain some insights into "more popular" translations based on inferences about the language the user is familiar with. It's e.g. very unlikely someone would be using an OS system language pack other than their native language.
