### ISSUE TITLE
Update doest add new languages to existing install

### ISSUE THREAD

**Issue by BaronKrause** [mozilla/firefox-translations#458]
**Describe the bug**
Most recent update that added multiple new languages including Italian and French does not actually update the list of available languages to choose from. You need to remove the extension and reinstall to get them to show.

**To Reproduce**
1. Let Extension update
2. New Languages are not on list

**Expected behavior**
Extension update to aply new settings to existing install.

**Screenshots**

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 104.0a1 (2022-07-23) (64-bit)
- Processor information:
- OS version: Linux (Pop!_OS 22.04)
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.3buildid20220722.083742
- Webpage on which issue was observed:
- Language of the webpage:
- Translating to (language):
- Console logs from Web Developer Tools:

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Additional context**
I tested this on 2 machines, both grabbed the update automatically today at the same time, and both did not have the new languages made available to them when testing, even after multiple browser restarts. Uninstalling and reinstalling the extension fixed this and showed the new full language list.

1 PC even had the settings get seemingly corrupted by the update, not allowing for any page to translate as the blue translate button always remained grayed out until reinstall.

**Comment by DawnPaladin** [comment]
I'm also seeing this problem, but uninstalling & reinstalling the extension did not provide the new languages.

**Comment by andrenatal** [comment]
I also reproduced this on OSX and Windows on Firefox 102. On OSX just restarting the browser fixed for me, but on Windows I needed to remove and install the addon again. 

The impression is that during the update some parts remained cached and stuck in the old version: in the screenshot below you can see that the displayed addon details are from 1.1.3 (notice that it doesn't include the new models for example), but the version shows as 1.1.2. On Windows I saw the exact opposite (details from 1.1.2 but version listed as 1.1.3). It seems that the update mechanism left some parts incomplete in a broken state.

I don't know if this is something fixable in the XPI itself, since we hadn't this issue in the previous updates, so I'll need help from the addons folks to evaluate what's happening here and see if someone know what's going on: @Rob--W @mixedpuppy @wagnerand  @rpl

<img width="682" alt="Screen Shot 2022-07-25 at 3 01 10 PM" src="https://user-images.githubusercontent.com/973388/180881958-8f378053-3b6f-48a2-bce3-df53be03f67b.png">

**Comment by Rob--W** [comment]
The screenshot above shows the description of the add-on. That information is indeed cached.

Is the bug only about the outdated add-on description, or is there something actually broken with the extension?

**Comment by andrenatal** [comment]
What I noticed was that although the notificationBox code was properly updated to the new version [1], the modelRegistry wasn't (hence the empty dropdown) so it seems that maybe getAPI here isn't being called in an update? [2].


[1]
<img width="517" alt="Screen Shot 2022-07-25 at 3 38 50 PM" src="https://user-images.githubusercontent.com/973388/180886694-4999dcd0-5d62-48ad-a4e4-f3b3aebeeec3.png">
 
[2] https://github.com/mozilla/firefox-translations/blob/456758f2cf26d0ba3dd07849b2fc14807fe85995/extension/controller/experiments/TranslationBar/api.js#L73

**Comment by andrenatal** [comment]
It also seems intermittent though. Tried to reproduce again on Windows and it just worked (but again after restarting the browser).

**Comment by andrenatal** [comment]
It seems #461 and #462 could be related to the same underlying issue causing this here.

**Comment by kpu** [comment]
After updating and restarting Firefox on Linux, when I go to French wikipedia the bar appears but the dropdown is blank and does no contain French.  
![fr](https://user-images.githubusercontent.com/247512/181042538-17757d66-0f37-4185-8b21-02270dd2736e.png)

**Comment by andrenatal** [comment]
I can consistently reproduce this in all channels. I've filed a bmo issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1781428
