### ISSUE TITLE
All languages in dropdown menu have "(beta)" near them

### ISSUE THREAD

**Issue by bicolino34** [mozilla/firefox-translations#480]
**Describe the bug**
In Ukrainian translation, every single language in dropdown menu has "(beta)" near them

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 103.0
- Processor information:
- OS version: 
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.3buildid20220722.083742
- Webpage on which issue was observed:
- Language of the webpage:
- Translating to (language):
- Console logs from Web Developer Tools:

**Comment by cadeyrn** [comment]
Since the Ukrainian model is still Beta, the described behaviour sounds expected to me.

**Comment by kpu** [comment]
Yes, everything is going through a not-so-good Ukrainian model.  A bit of back story is this particular model came from OPUS on not much data.  Then I used the model to run ParaCrawl to mine the web for more parallel data: http://web-language-models.s3-website-us-east-1.amazonaws.com/paracrawl/bonus/en-uk-v1.txt.gz .  

There's even more data in the WMT task on Ukrainian: https://www.statmt.org/wmt22/translation-task.html

But we haven't gotten around to building a newer model on that data.

**Comment by bicolino34** [comment]
You mean that if Ukrainian language is in beta then all other will also have beta near them in dropdown menu?
Example: English (Beta)
![image](https://user-images.githubusercontent.com/58372007/181877390-ad8387af-2823-4b9f-a378-1e5a68184ee5.png)

**Comment by kpu** [comment]
Internally, we have translation directions.  It's not a multilingual model at present, so there's a Ukrainian -> English model and an English -> Ukrainian model.  If we need, say, Bulgarian then it is pivoting by translating Bulgarian -> English and English -> Ukrainian.  The UI attempts to simplify this into support for particular languages.  

Beta is really a word that means "don't judge us too hard on quality because we know we can do better".  And the quality of all translations into Ukrainian is not as good as it could be.  

I accept the outcome in the UI is weird and it could be explained better.

**Comment by bicolino34** [comment]
Ok, thank you for explanation. I didn't know that. Should I keep the issue, or better close it?

**Comment by andrenatal** [comment]
As explained, this is the expected behavior, thanks @bicolino34
