### ISSUE TITLE
Spanish to English mistranslation

### ISSUE THREAD

**Issue by birdsarah** [mozilla/firefox-translations#495]
Website: https://www.argentina.gob.ar/inadi

**Input**:

Discriminación a Personas Gordas
Grupo de Trabajo que construye herramientas de difusión, informes e investigaciones para la erradicación de la gordofobia.

**Output from Firefox translations:**

Discrimination against Fat Persons
Working Group that builds dissemination tools, reports and research for the eradication of fat dogphobia.

**Expected result:**
Only one correction "la gordofobia" should be "fatphobia" not "fat dogphobia."

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported this problem, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
