### ISSUE TITLE
"This page is not in <LANGUAGE>" option when wrong language is detected

### ISSUE THREAD

**Issue by tyilo** [mozilla/firefox-translations#506]
**Is your feature request related to a problem? Please describe.**
When visiting a site in English but the translation extensions thinks the page is in Italian, there is no way to inform the extension that the detected language is wrong.

Instead the only options are:
- Never translate this site (I might want to translate other pages on this site, if they're in another language)
- Never translate Italian (I might want to translate Italian, but this page is not in Italian)

**Describe the solution you'd like**
I think another option should be added:
- This page is not in Italian

Of course fixing the detection for the particular site would be nice, but I still think we should have the option.

**Describe alternatives you've considered**
- Dismissing the translation bar, but then it just shows up the next time you visit the page
- Using "Never translate this site", but I might want to translate other pages on this site, if they're in another language

**Additional context**
Currently this happens with Firefox Developer Edition 105.0b4 and Extension Version 1.1.4buildid20220803.111909 on the site https://wavvy.app/

**Comment by forteller** [comment]
I came here to ask for this functionality. It thinks Norwegian is Spanish from time to time.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I think this is less of a problem in the built-in version, as there is a menu item in the main Firefox menu to translate pages. Feel free to file a bug on [Bugzilla](https://bugzilla.mozilla.org/) if you think of additional improvements we could make.
