### ISSUE TITLE
[Feature] Add "Show original content/webpage" button - Switch back to original language of the page

### ISSUE THREAD

**Issue by Soromeister** [mozilla/firefox-translations#517]
**Is your feature request related to a problem? Please describe.**
After using the translate feature, sometimes, the web forms might send invalid POST requests. To avoid this, I generally complete the web forms using English, after which I switch to original language and then press send.

**Describe the solution you'd like**
After doing the translation, have a button to switch back to original language of the web page, effectively undo-ing the translation. Basically, un-translate the contents.

**Describe alternatives you've considered**
For regular web pages, pressing reload will re-load the entire page in the original language. For pages that belong to a session, this won't work, so this is why I am requesting this feature.

**Additional context**
N/A

**Comment by kpu** [comment]
Try the "stop translating" button on https://addons.mozilla.org/en-US/firefox/addon/translatelocally-for-firefox/

**Comment by Soromeister** [comment]
@kpu , That is a totally different add-on and it doesn't even support the same languages like the Firefox Translations does.

**Comment by kpu** [comment]
@Soromeister That extension is effectively the development version.  I'd like to hear your feedback.  Your point about language support is taken; we could restore the beta languages (which have lower quality) and effort is underway to support far more languages.  Are there issues beyond language support when you compare the two extensions?

**Comment by sylvestre** [comment]
Sorry, I removed some comments as they were out of topic.

I agree that it is a nice feature to have. The first implementation could do just a refresh of the page.

**Comment by jelmervdl** [comment]
The [code](https://github.com/jelmervdl/translatelocally-web-ext/blob/main/src/content/InPageTranslation.js) that the [in-page translation implementation](https://github.com/mozilla/firefox-translations/blob/main/extension/view/js/InPageTranslation.js) is based on [supports this](https://github.com/jelmervdl/translatelocally-web-ext/pull/34/files). Someone could test and contribute this back to this add-on.

> After using the translate feature, sometimes, the web forms might send invalid POST requests.

That should not happen, regardless of whether you translated the page or not. As far as I'm aware, the add-on never touches anything that affects a form field (e.g. `<input type="button">` labels or `<input type="hidden">` values…) Do you have an example of a page that breaks? Because that sounds like a bug or at least a situation we should avoid.
