### ISSUE TITLE
Weird French -> English translation

### ISSUE THREAD

**Issue by drchriscole** [mozilla/firefox-translations#691]
### Describe the bug

This french phrase:
"Paramètre physiologique ou biologique mesurable, qui permet par exemple de diagnostiquer ou de suivre l’évolution d’une maladie."

Is translated into English:
"Meatable or biological parameter, such as diagnosing or monitoring the course of a disease."

Meatable is not an English word. The translation should be physiological.

### To Reproduce

1. Go to: https://www.inserm.fr/actualite/ht-advance-vers-une-meilleure-prise-en-charge-clinique-de-lhypertension-arterielle/
2. Translate into Enlish
3. Hover over the 'Biomarkers' definition at the end of the third paragraph
4. See the word 'meatable'.

### Expected behavior

The correct translation of the french 'physiologique' should be 'physiological'.

### Firefox Browser version

111.0

### Processor information

Intel i3-8100

### OS version

Windows 10 Pro 21H2

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

https://www.inserm.fr/actualite/ht-advance-vers-une-meilleure-prise-en-charge-clinique-de-lhypertension-arterielle/

### Language of the webpage

French

### Translating to (language)

English

**Comment by HumanistAtypik** [comment]
I can testify that the **French texts I get via Firefox Translations are often less comprehensible than their English source text**; I am, however, a lifelong French speaker, a writer by profession and a very imperfect English speaker...
The project is excellent - and I strongly encourage it - but the mountain to climb to pull the flying carpet out from under the Gafam & co.
Courage, then!

**_Translated with www.DeepL.com/Translator (free version) from:_**
_"Je peux témoigner que les textes en langue française que j'obtiens via Firefox Translations me sont souvent moins compréhensibles que leur texte-source anglophone ; je suis pourtant francophone depuis toujours, rédacteur de profession et très imparfaitement anglophone...
Le projet est excellent - et je l'encourage vivement - mais haute encore est la montagne à gravir pour tirer le tapis volant de dessous les fesses des Gafam & cie...
Courage, donc !"_

**_Here is the Google Translate French-to-English result:_**
_"I can testify that the texts in French that I obtain via Firefox Translations are often less understandable to me than their English-language source text; I have always been a French-speaker, however, a writer by profession and very imperfectly English-speaking...
The project is excellent - and I strongly encourage it - but still high is the mountain to climb to pull the magic carpet from under the buttocks of Gafam & cie...
Courage, then!"_

_**Then Microsoft Translator's:**_
_"I can testify that the French texts I obtain via Firefox Translations are often less comprehensible to me than their English source text; However, I have always been French-speaking, an editor by profession and very imperfectly English-speaking...
The project is excellent - and I strongly encourage it - but still high is the mountain to climb to pull the flying carpet from under the buttocks of Gafam & cie...
Courage, then!"_

_**And here is Firefox's:**_
_"I can testify that the French-language texts I obtain via Firefox Translations are often less comprehensible to me than their English-language text-source; I have always been French-speaking, professional editor and very imperfectly English-speaking...
The project is excellent - and I strongly encourage it - but still high is the mountain to climb to pull the carpet flying under the buttocks of the Gafam and this...
Courage, so."_

### As far as I can tell, the from-French-to-English results of Firefox are quite better than from-English-to-French one...

**Comment by marco-c** [comment]
Here's the funny thing:
`Paramètre physiologique ou biologique mesurable, qui permet par exemple de diagnostiquer ou de suivre l’évolution d’une maladie` -> Meatable or biological parameter, which makes it possible, for example, to diagnose or monitor the course of a disease 
`Paramètre physiologique ou biologique mesurable, qui permet par exemple de diagnostiquer ou de suivre l’évolution d’une maladie.` -> Meatable or biological parameter, such as diagnosing or monitoring the course of a disease.
`"Paramètre physiologique ou biologique mesurable, qui permet par exemple de diagnostiquer ou de suivre l’évolution d’une maladie"` -> "Meatable or measurable biological parameter, which makes it possible, for example, to diagnose or monitor the course of a disease" 
`"Paramètre physiologique ou biologique mesurable, qui permet par exemple de diagnostiquer ou de suivre l’évolution d’une maladie."` -> "Measurable physiological or biological parameter, which makes it possible, for example, to diagnose or monitor the course of a disease." 

Anyway, we are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported this problem, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
