### ISSUE TITLE
Questionable Italian -> English translation

### ISSUE THREAD

**Issue by AJRMcCann** [mozilla/firefox-translations#697]
To test the translation add-on I went to the Italian wiki page for Cambridge University (https://it.wikipedia.org/wiki/Universit%C3%A0_di_Cambridge). There were a number of issues that jumped out:

- "inglese" is not translated.
- "Located in the City of East Anglia" should be "Located in the City of Cambridge, in East Anglia".
- "a 204-year lapse" has been translated to "a 204-year groceries", which is confusing!
- "you are in total in Cambridge" should be "six in total in Cambridge"

I hope this is indicative of some of the issues found!

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported these problems, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
